### ISSUE TITLE
Unable to get custom command working

### ISSUE THREAD

**Issue by ChristopherHaws** [FlashyReese/CommandAliases#37]
Hello!

I have created a file called `tpsbar.yaml` in the `commandaliases` directory with the following contents:
```
commandMode: COMMAND_CUSTOM
customCommand:
  parent: tpsbar
  actions:
    - command: tabtps toggle bossbar
      commandType: SERVER
```

When I load the server and type `/tpsbar`, it doesn't give autocompletion and the command says it doesn't exist. I can't figure out what I am doing wrong. Any help would be appreciated ^_^
