### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by Basgamer999** [FlashyReese/CommandAliases#53]
I followed the wiki trying to create a custom command that switch between spectator and creative but its not working when i add the unsuccesful part
`schemaVersion = 1
commandMode = "COMMAND_CUSTOM"
command = "gmode"

[[actions]]
id = "generic"
command = "gamemode spectator $executor_name()"
commandType = "SERVER"
requireSuccess = false
messageIfUnsuccessful = "Test"

[[actionsIfUnsuccessful]]
command = "gamemode creative $executor_name()"
commandType = "SERVER"
requireSuccess = false
messageIfUnsuccessful = "Test"`
This is the .toml file i got but i just get a error that it not load:
`[12:29:55] [Server thread/ERROR]: Failed to load file at "/home/container/./config/commandaliases/g-mode.toml" throws com.fasterxml.jackson.dataformat.toml.TomlStreamReadException: Newline not permitted here
 at [Source: (File); line: 12, column: 22]`

**Comment by FlashyReese** [comment]
Sorry for the late response, you can achieve the following with
```toml
schemaVersion = 1
commandMode = "COMMAND_CUSTOM"
command = "gmode"

[[actions]]
command = "gamemode spectator $executor_name()"
commandType = "SERVER"

[[actions.actionsIfUnsuccessful]]
command = "gamemode creative $executor_name()"
commandType = "SERVER"
```

`[[actions.actionsIfUnsuccessful]]` you didn't have the property inside of said action.
